#!/bin/bash
# The ping my Lan script

date
#date +"%FORMAT"
var=$(date)
var='date'

i="1"
while [ 1 ]
do
    now=$(date)
    echo ""
    echo "Checking home LAN ($i)"
    echo "$now"

    if ping -c 1 shed &>/dev/null
    then
        echo "[OK] shed is online."
    else
        echo "[ERROR] shed is unavailable!"
    fi

    if ping -c 1 garage &>/dev/null
    then
        echo "[OK] garage is online."
    else
        echo "[ERROR] garage is unavailable!"
    fi

    if ping -c 1 kehano &>/dev/null
    then
        echo "[OK] kehano is online."
    else
        echo "[ERROR] kehano is unavailable!"
    fi

    if ping -c 1 oldmonkey &>/dev/null
    then
        echo "[OK] oldmonkey is online."
    else
        echo "[ERROR] oldmonkey is unavailable!"
    fi

    if ping -c 1 spaceman &>/dev/null
    then
        echo "[OK] spaceman is online."
    else
        echo "[ERROR] spaceman is unavailable!"
    fi
    sleep 60
 
    i=$[$i+1] 
done
